# ============================================================
# CI/CD Pipeline for Azure Web App + Security Scans
# Includes: Build → CodeQL (SAST) → Deploy → OWASP ZAP (DAST)
# ============================================================

name: Build, Scan, and Deploy Python app to Azure Web App - SmartCertify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ======================
  # 1️⃣ Build Job
  # ======================
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # change if your app uses another version

      - name: Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

  # ======================
  # 2️⃣ Static Code Scan (CodeQL)
  # ======================
  codeql:
    name: Run CodeQL SAST Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # ======================
  # 3️⃣ Deploy Job
  # ======================
  deploy:
    runs-on: ubuntu-latest
    needs: [build, codeql]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC539B19E25248EBA2EB19B070A26992 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B3BB1464A2764AA99CB38E2BBE1A67D5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3081A9A2B18D4D7085DE13F1C567B79F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'SmartCertify'
          slot-name: 'Production'

  # ======================
  # 4️⃣ Dynamic App Scan (OWASP ZAP)
  # ======================
  dast:
    name: Run OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "https://smartcertify.azurewebsites.net"
          cmd_options: "-a" # active scan mode

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
            report_md.md
