name: ZAP Baseline Security Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare report directory
        run: |
          mkdir -p zap_reports
          chmod 777 zap_reports

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://smartcertify-ewbsesghf9ftcwfd.southindia-01.azurewebsites.net/'
          allow_issue_writing: false
          cmd_options: '-J zap_reports/report_json.json -w zap_reports/report_md.md -r zap_reports/report_html.html -a'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_reports/
