name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"  # runs once every Sunday
  workflow_dispatch:      # allows manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP Baseline Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://smartcertify.azurewebsites.net'
          cmd_options: '-a' # active scan mode
          rules_file_name: '.zap/rules.tsv'
          allow_issue_writing: false

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: |
            report_html.html
            report_json.json
            report_md.md
