name: OWASP ZAP Security Scan

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main
      - master

jobs:
  zap_scan:
    name: Run OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix folder permissions
        run: sudo chmod -R 777 ${{ github.workspace }}

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://smartcertify.azurewebsites.net'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: report_html.html
